// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/Compogo/resource/resource/resource.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Type                   `protobuf:"varint,1,opt,name=Type,proto3,enum=compogo.resource.resource.Type" json:"Type,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Usage         uint64                 `protobuf:"varint,3,opt,name=Usage,proto3" json:"Usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_github_com_Compogo_resource_resource_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Compogo_resource_resource_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_github_com_Compogo_resource_resource_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Memory
}

func (x *Resource) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Resource) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

var File_github_com_Compogo_resource_resource_resource_proto protoreflect.FileDescriptor

const file_github_com_Compogo_resource_resource_resource_proto_rawDesc = "" +
	"\n" +
	"3github.com/Compogo/resource/resource/resource.proto\x12\x19compogo.resource.resource\x1a/github.com/Compogo/resource/resource/type.proto\"k\n" +
	"\bResource\x123\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x1f.compogo.resource.resource.TypeR\x04Type\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x04R\x05Limit\x12\x14\n" +
	"\x05Usage\x18\x03 \x01(\x04R\x05UsageB/Z-github.com/Compogo/resource/protobuf/resourceb\x06proto3"

var (
	file_github_com_Compogo_resource_resource_resource_proto_rawDescOnce sync.Once
	file_github_com_Compogo_resource_resource_resource_proto_rawDescData []byte
)

func file_github_com_Compogo_resource_resource_resource_proto_rawDescGZIP() []byte {
	file_github_com_Compogo_resource_resource_resource_proto_rawDescOnce.Do(func() {
		file_github_com_Compogo_resource_resource_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Compogo_resource_resource_resource_proto_rawDesc), len(file_github_com_Compogo_resource_resource_resource_proto_rawDesc)))
	})
	return file_github_com_Compogo_resource_resource_resource_proto_rawDescData
}

var file_github_com_Compogo_resource_resource_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_Compogo_resource_resource_resource_proto_goTypes = []any{
	(*Resource)(nil), // 0: compogo.resource.resource.Resource
	(Type)(0),        // 1: compogo.resource.resource.Type
}
var file_github_com_Compogo_resource_resource_resource_proto_depIdxs = []int32{
	1, // 0: compogo.resource.resource.Resource.Type:type_name -> compogo.resource.resource.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_Compogo_resource_resource_resource_proto_init() }
func file_github_com_Compogo_resource_resource_resource_proto_init() {
	if File_github_com_Compogo_resource_resource_resource_proto != nil {
		return
	}
	file_github_com_Compogo_resource_resource_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Compogo_resource_resource_resource_proto_rawDesc), len(file_github_com_Compogo_resource_resource_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Compogo_resource_resource_resource_proto_goTypes,
		DependencyIndexes: file_github_com_Compogo_resource_resource_resource_proto_depIdxs,
		MessageInfos:      file_github_com_Compogo_resource_resource_resource_proto_msgTypes,
	}.Build()
	File_github_com_Compogo_resource_resource_resource_proto = out.File
	file_github_com_Compogo_resource_resource_resource_proto_goTypes = nil
	file_github_com_Compogo_resource_resource_resource_proto_depIdxs = nil
}
