// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: github.com/Compogo/resource/resource/type.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Memory Type = 0
	Type_CPU    Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Memory",
		1: "CPU",
	}
	Type_value = map[string]int32{
		"Memory": 0,
		"CPU":    1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Compogo_resource_resource_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_github_com_Compogo_resource_resource_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Compogo_resource_resource_type_proto_rawDescGZIP(), []int{0}
}

var File_github_com_Compogo_resource_resource_type_proto protoreflect.FileDescriptor

const file_github_com_Compogo_resource_resource_type_proto_rawDesc = "" +
	"\n" +
	"/github.com/Compogo/resource/resource/type.proto\x12\x19compogo.resource.resource*\x1b\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06Memory\x10\x00\x12\a\n" +
	"\x03CPU\x10\x01B/Z-github.com/Compogo/resource/protobuf/resourceb\x06proto3"

var (
	file_github_com_Compogo_resource_resource_type_proto_rawDescOnce sync.Once
	file_github_com_Compogo_resource_resource_type_proto_rawDescData []byte
)

func file_github_com_Compogo_resource_resource_type_proto_rawDescGZIP() []byte {
	file_github_com_Compogo_resource_resource_type_proto_rawDescOnce.Do(func() {
		file_github_com_Compogo_resource_resource_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Compogo_resource_resource_type_proto_rawDesc), len(file_github_com_Compogo_resource_resource_type_proto_rawDesc)))
	})
	return file_github_com_Compogo_resource_resource_type_proto_rawDescData
}

var file_github_com_Compogo_resource_resource_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Compogo_resource_resource_type_proto_goTypes = []any{
	(Type)(0), // 0: compogo.resource.resource.Type
}
var file_github_com_Compogo_resource_resource_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_Compogo_resource_resource_type_proto_init() }
func file_github_com_Compogo_resource_resource_type_proto_init() {
	if File_github_com_Compogo_resource_resource_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Compogo_resource_resource_type_proto_rawDesc), len(file_github_com_Compogo_resource_resource_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Compogo_resource_resource_type_proto_goTypes,
		DependencyIndexes: file_github_com_Compogo_resource_resource_type_proto_depIdxs,
		EnumInfos:         file_github_com_Compogo_resource_resource_type_proto_enumTypes,
	}.Build()
	File_github_com_Compogo_resource_resource_type_proto = out.File
	file_github_com_Compogo_resource_resource_type_proto_goTypes = nil
	file_github_com_Compogo_resource_resource_type_proto_depIdxs = nil
}
