// Code generated by "stringer --type=Version"; DO NOT EDIT.

package cgroup

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CGroupV1-0]
	_ = x[CGroupV2-1]
}

const _Version_name = "CGroupV1CGroupV2"

var _Version_index = [...]uint8{0, 8, 16}

func (i Version) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Version_index)-1 {
		return "Version(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Version_name[_Version_index[idx]:_Version_index[idx+1]]
}
